### ISSUE TITLE
[PWK] improvement: install bash and kubectl completion

### ISSUE THREAD

**Issue by jjo** [play-with-docker/play-with-docker#183] opened 2017-08-15 18:54 UTC
FYI to make my `kubectl` sessions more usable, I usually do:

```
yum install -y bash-completion
kubectl completion bash > /etc/bash_completion.d/kubectl.bash
exec bash
```

**Comment by marcosnils** [comment] 2017-08-15 19:00
dupe of #164 .

**Closed by marcosnils** 2017-08-15 19:00 UTC
