### ISSUE TITLE
Try in PWD button does not launch the stack

### ISSUE THREAD

**Issue by pifou25** [play-with-docker/play-with-docker#589] opened 2023-06-10 10:07 UTC
Hello,

I try to add the "Try with PWD" button in the readme so that users can test the application online. This is the link

https://labs.play-with-docker.com/?stack=https://raw.githubusercontent.com/pifou25/jeedom-core/pwd/docker-compose.yml

The stack is ok : https://raw.githubusercontent.com/pifou25/jeedom-core/pwd/docker-compose.yml 

But when opening the Try-With-Docker, nothing build, session says to be ready but does nothing, no error displayed:
![image](https://github.com/play-with-docker/play-with-docker/assets/20190031/d70a40bd-65f6-45bc-b064-5c4a084304e2)

Something is missing, when I run these commands, it works : 
```
wget https://raw.githubusercontent.com/pifou25/jeedom-core/pwd/docker-compose.yml 
docker-compose up -d
```

**Comment by pifou25** [comment] 2023-06-25 14:35
Hello, there is now an error in the modal popup:

`Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?`

Seems like the only missing is ... Docker daemon ?

**Comment by RawSanj** [comment] 2023-12-22 06:30
Looks like the `stack` URL query parameter is not working anymore. 

The `wget compose-file-url && docker-compose up -d` is working fine. But without the stack URL, the PWD Button won't work. 😞

**Comment by mgramin** [comment] 2024-01-12 12:33
We have exactly the same problem (and on all the "Try with PWD" buttons that I've seen too).
Could you clarify whether this is the expected behavior and the `stack` URL parameter will no longer be supported, or can we hope for a fix? Can we assist in any way?

**Comment by marcosnils** [comment] 2024-01-12 13:26
checking

**Comment by marcosnils** [comment] 2024-01-12 14:22
should be fixed now

**Closed by marcosnils** 2024-01-12 14:22 UTC
