### ISSUE TITLE
Cannot access PWD remotely - gets 503 Service not available

### ISSUE THREAD

**Issue by Halfwalker** [play-with-docker/play-with-docker#135] opened 2017-05-05 20:15 UTC
Not sure this is an issue, more like a "whups, doing it wrong" ...

I spun up PWD on a VM in our vsphere farm.  It's an Ubuntu 16.04 system with current docker 17.04.0-ce, a fairly standard setup we have.  Ran the following to bring up PWD

```
git clone https://github.com/franela/play-with-docker  
cd play-with-docker/  
docker pull franela/dind

sudo apt install golang-go
sudo modprobe xt_ipvs

export GOPATH=$HOME/.go  
go get -v -d -t ./...  
docker-compose up
```

PWD appears to come up.

> Attaching to proxy, pwd2, pwd1
> proxy      | <7>haproxy-systemd-wrapper: executing /usr/local/sbin/haproxy -p /run/haproxy.pid -f /usr/local/etc/haproxy/haproxy.cfg -Ds
> pwd1       | 2017/05/05 20:04:15 Listening TLS on port 3001
> pwd1       | 2017/05/05 20:04:15 Listening on port 3000
> pwd2       | 2017/05/05 20:04:15 Listening TLS on port 3001
> pwd2       | 2017/05/05 20:04:15 Listening on port 3000
> pwd1       | [negroni] 2017-05-05T20:04:16Z | 0 | 	 388.775µs |  | GET /ping
> pwd2       | [negroni] 2017-05-05T20:04:18Z | 0 | 	 375.096µs |  | GET /ping

Connecting from a local workstation just gets a 503 Service unavailable.  A wget on the VM shows that PWD is up and working though ...

**Comment by marcosnils** [comment] 2017-05-07 18:12
@Halfwalker seems like you got it right. If the wget works in the instance but you can't access from the outside, it looks like a different kind of problem.. Not sure how to help you diagnose, you shouldn't need to do anything else.

**Comment by Halfwalker** [comment] 2017-05-07 22:12
Yah, it's very strange.  I'm trying it in a local Vmware Fusion VM, at ip 192.168.2.162.  Then trying to hit it from my workstation at 192.168.2.101.  The VM is running with bridged networking, so it's on the same network as the local workstation.  Here's a pcap from the PWD VM itself (**sudo tshark not port 22 and host 192.168.2.162**) ...
```
  5 3.056653537 192.168.2.101 -> 192.168.2.162 TCP 74 44964 → 80 [SYN] Seq=0 Win=26880 Len=0 MSS=8960 SACK_PERM=1 TSval=87278919 TSecr=0 WS=128
  6 3.056765418 192.168.2.162 -> 192.168.2.101 TCP 74 80 → 44964 [SYN, ACK] Seq=0 Ack=1 Win=28960 Len=0 MSS=1460 SACK_PERM=1 TSval=43845278 TSecr=87278919 WS=128
  7 3.057044661 192.168.2.101 -> 192.168.2.162 TCP 66 44964 → 80 [ACK] Seq=1 Ack=1 Win=26880 Len=0 TSval=87278919 TSecr=43845278
  8 3.057292551 192.168.2.101 -> 192.168.2.162 HTTP 498 GET / HTTP/1.1 
  9 3.057392472 192.168.2.162 -> 192.168.2.101 HTTP 278 HTTP/1.0 503 Service Unavailable  (text/html)
 10 3.061154174 192.168.2.101 -> 192.168.2.162 TCP 66 44964 → 80 [FIN, ACK] Seq=433 Ack=214 Win=28032 Len=0 TSval=87278920 TSecr=43845278
 11 3.061258425 192.168.2.162 -> 192.168.2.101 TCP 66 80 → 44964 [ACK] Seq=214 Ack=434 Win=30080 Len=0 TSval=43845279 TSecr=87278920

```
Totally ordinary connection, SYN, SYN-ACK, ACK, then the GET, then the immediate 503.
Yet here's the curl from the VM itself, which works ...
```
$ curl localhost
<!doctype html>
<html ng-app="DockerPlay" ng-controller="BypassController">
    <head>
        <title>Docker Playground</title>
	    <link rel="stylesheet" href="http://ajax.googleapis.com/ajax/libs/angular_material/1.1.0/angular-material.min.css">
        <link rel="stylesheet" href="/assets/style.css" />
    </head>
    <body class="welcome">
        <div>
            <h1>Welcome!</h1>
            <h2>We're bypassing the Captcha and redirecting you now..</h2>
            <form id="welcomeFormBypass" method="POST" action="/">
                <button id="start" type="submit">Start Session</button>
            </form>
        </div>
    </body>
         :
```
and the pcap (**sudo tshark -i lo**) - which is over ipv6.  Hrmm ...
```
 16 2.918036746          ::1 -> ::1          TCP 94 51392 → 80 [SYN] Seq=0 Win=43690 Len=0 MSS=65476 SACK_PERM=1 TSval=43939827 TSecr=0 WS=128
 17 2.918117032          ::1 -> ::1          TCP 94 80 → 51392 [SYN, ACK] Seq=0 Ack=1 Win=43690 Len=0 MSS=65476 SACK_PERM=1 TSval=43939827 TSecr=43939827 WS=128
 18 2.918129227          ::1 -> ::1          TCP 86 51392 → 80 [ACK] Seq=1 Ack=1 Win=43776 Len=0 TSval=43939827 TSecr=43939827
 19 2.918642675          ::1 -> ::1          HTTP 159 GET / HTTP/1.1 
 20 2.918651059          ::1 -> ::1          TCP 86 80 → 51392 [ACK] Seq=1 Ack=74 Win=43776 Len=0 TSval=43939827 TSecr=43939827
 21 2.925849453          ::1 -> ::1          HTTP 1394 HTTP/1.1 200 OK  (text/html)
 22 2.925854621          ::1 -> ::1          TCP 86 51392 → 80 [ACK] Seq=74 Ack=1309 Win=174720 Len=0 TSval=43939829 TSecr=43939829
 23 2.925931958          ::1 -> ::1          TCP 86 51392 → 80 [FIN, ACK] Seq=74 Ack=1309 Win=174720 Len=0 TSval=43939829 TSecr=43939829
 24 2.928092158          ::1 -> ::1          TCP 86 80 → 51392 [FIN, ACK] Seq=1309 Ack=75 Win=43776 Len=0 TSval=43939830 TSecr=43939829
 25 2.928096180          ::1 -> ::1          TCP 86 51392 → 80 [ACK] Seq=75 Ack=1310 Win=174720 Len=0 TSval=43939830 TSecr=43939830
 ```

**Comment by marcosnils** [comment] 2017-05-07 23:35
@Halfwalker I think I know that the problem is. When running PWD locally through haproxy, we expect the hostname `localhost` to be used (https://github.com/play-with-docker/play-with-docker/blob/master/haproxy/haproxy.cfg#L10-L16). If you're trying to access the VM through the IP address it won't work. 

You have two alternatives: 

1. You can change the haproxy config file to use some other host you like. 

2. You can map the VM ip address to `localhost` in your machine.

**Comment by Halfwalker** [comment] 2017-05-08 13:30
Ah ha !  That was it.  Closer now ...
```
pwd2       | [negroni] 2017-05-08T13:27:48Z | 0 | 	 212.045µs |  | GET /ping
pwd1       | [negroni] 2017-05-08T13:27:49Z | 200 | 	 6.035814ms | triage2srv.local | GET /
pwd1       | [negroni] 2017-05-08T13:27:49Z | 200 | 	 1.777782ms | triage2srv.local | GET /assets/app.js
pwd2       | [negroni] 2017-05-08T13:27:49Z | 200 | 	 4.931284ms | triage2srv.local | GET /assets/style.css
pwd2       | [negroni] 2017-05-08T13:27:50Z | 200 | 	 228.795µs | triage2srv.local | GET /instances/images
pwd1       | [negroni] 2017-05-08T13:27:50Z | 404 | 	 109.201µs | triage2srv.local | GET /favicon.ico
pwd2       | 2017/05/08 13:27:50 NewSession id=[0fbcd776-1292-49e4-8a2a-667a2d912f5c]
pwd2       | 2017/05/08 13:27:50 Starting session err [Error response from daemon: datastore for scope "global" is not initialized]
pwd2       | 2017/05/08 13:27:50 ERROR NETWORKING
pwd2       | 2017/05/08 13:27:50 Error response from daemon: datastore for scope "global" is not initialized
pwd2       | [negroni] 2017-05-08T13:27:50Z | 0 | 	 5.692608ms | triage2srv.local | POST /
pwd1       | [negroni] 2017-05-08T13:27:51Z | 0 | 	 190.163µs |  | GET /ping
```

**Comment by marcosnils** [comment] 2017-05-08 13:32
That's because your docker daemon is not in swarm mode. Check the README instructions as it's stated there.

**Comment by Halfwalker** [comment] 2017-05-08 13:55
Heh, yup, figured that out.  did the `docker swarm init` before the `docker-compose up` and now I can it hit.  But then it does a redirect/whatever to
```
http://host1.triage2srv.local/p/dc339af2-27f4-4df8-86d5-a259f71b4f19
```
which of course fails to resolve.  The VM this is running on is `triage2srv.local`

**Comment by Halfwalker** [comment] 2017-05-08 16:57
It would be nice if instead of **pre**-pending the _host1_ to the url, it put that into the url itself ? So `host1.triage2srv.local/p/dc....` becomes `triage2srv.local/host1/p/dc.....`
Could that work ?

**Comment by marcosnils** [comment] 2017-05-08 17:01
> It would be nice if instead of pre-pending the host1 to the url, it put that into the url itself ? So host1.triage2srv.local/p/dc.... becomes triage2srv.local/host1/p/dc.....
> Could that work ?

Nope because of routing issues.

What you need to do is to make *.triage2srv.local to resolve localhost.

**Comment by Halfwalker** [comment] 2017-05-08 17:09
Hrm - I'm using avahi on the VM for name resolution - hence the .local domain.  Should be able to inject CNAME entries into the mdns for that.  Will play with it.

**Comment by marcosnils** [comment] 2017-05-08 17:12
I'll close this issue as the original problem has been fixed.

**Closed by marcosnils** 2017-05-08 17:12 UTC

**Comment by Halfwalker** [comment] 2017-05-08 17:41
Dang - so close yet so far.  I put entries in /etc/hosts to point triage2srv.local, host1.triage2srv.local and host2.triage2srv.local to the VM IP address.  The initial connection works, but then the `http://host2.triage2srv.local/p/8e8a849a-f31c-4795-8785-7319b597dda0` url comes back with a 503.  So it's hitting correctly, but something else isn't right ...

**Comment by marcosnils** [comment] 2017-05-08 17:47
Seems like haproxy can't deliver the request. Did you change the haproxy config file?

**Comment by Halfwalker** [comment] 2017-05-08 17:51
Yah - me dumb.  Only changed the main ACL `acl host_localhost hdr(host) triage2srv.local` - totally didn't change the other two for host1/host2.  It's working now :)  Thanks.
