### ISSUE TITLE
Abrupt PWD session timeout (Container Training ELK sample)

### ISSUE THREAD

**Issue by marcianomoreno** [play-with-docker/play-with-docker#545] opened 2022-07-27 04:35 UTC
PWD session ends abruptly a few seconds after cloning [container.training](http://github.com/naylalex/container.training) 
 repository and issuing `docker compose up` on the ELK sample found in container.training/elk.
Environment id: cbgbtb2v_cbgbtcav7vjg00b0chag
SSH connection: ssh ip172-18-0-78-cbgbtb2v7vjg00b0cha0@direct.labs.play-with-docker.com

I experienced similar issues today morning on PWD with other docker-related commands.

![PWD1](https://user-images.githubusercontent.com/7190962/181162026-d107e5f0-bdcf-473c-82eb-eea3f16670e7.PNG)
![PWD2](https://user-images.githubusercontent.com/7190962/181162043-a40267b0-25d2-4e27-b40b-0cc1db742ec1.PNG)

**Comment by marcosnils** [comment] 2022-07-27 14:32
Dupe of #530. Check https://github.com/play-with-docker/play-with-docker/issues/530#issuecomment-1163865529

**Closed by marcosnils** 2022-07-27 14:32 UTC
