### ISSUE TITLE
any provision to cache pulls of large images, across sessions?

### ISSUE THREAD

**Issue by carehart** [play-with-docker/play-with-docker#342] opened 2019-06-22 16:31 UTC
I'm asking this regarding the PWD site/service, not a local deployment of PWD: and first, thanks for that wonderful playground to help folks getting started with Docker, etc.

But for your sake, is there any provision to cache pulls of a very large image (approx a gig) across multiple sessions, by a user or many users, for perhaps a day or week? 

As it stands, after each 4-hour window, a pull of the same image really does a complete pull, because (understandably) you're presenting to users a blank slate on each new session, with no presumed local cache of pulls. 

But consider someone who may use a given large image over multiple sessions or days. Or someone lead multiple folks to use PWD with some given large image while leading a user group session, class, etc. Each one doing the pull experiences slowness as the image is pulled down for "the first time" for them.

I wonder: how about perhaps offering a "local" PWD registry (local to the PWD site), where we (who may be willing to use such a registry in our examples) would then just tell folks to use it in instead, for the sake of speed. And you could impose a limit of a day or something for how long you'd be willing to hold the cache of images there.  

I certainly appreciate that there are disk costs for you to keep such a large image available across sessions, or users. I just wonder what the balance may be between that cost and the bandwidth costs of multiple pulls of a large image within a day or some days, by one or many users.

You might even be able to charge for access to it, where an instructor or vendor showing something in a class for a day might be willing to pay a small fee to make those pulls go faster for that one day or week. 

All that said, I have not yet implemented registries, so I don't know if there's provision to have the registry automatically pull down an image if it's been deleted. That would be pretty key to this working. As I look into it, I see a means for a registry to auto purge after a number of hours or days. It's not clear what happens if a pull is done against an image that has been purged. 

Apologies for any ignorance on my part in any of this, and also for it being a long note. I realize some responding may merely skim it, which could present challenges in subsequent back and forth. I did try to find if the issue and any solutions had been discussed already here, and I could not.

And I realize this whole issue may have complications I'm not even considering. I just wanted to see if anyone had given thought to it.Thanks.

**Comment by marcosnils** [comment] 2019-06-22 22:34
> I'm asking this regarding the PWD site/service, not a local deployment of PWD: and first, thanks for that wonderful playground to help folks getting started with Docker, etc.

Thanks!

In regards to the image caching, we do offer that functionality but it's a paid version of PWD that's suited for workshops or companies that need it for internal courses. 

As it's mostly an `infra` related problem, there's not much we can do from the open source perspective to offer a solution for that. As you said, it requires using private registries and dedicated extra storage to accomplish such task. 

I'll close this as there's not much we can do about it ATM.

**Closed by marcosnils** 2019-06-22 22:34 UTC

**Comment by carehart** [comment] 2019-06-23 02:44
Thanks, but could you please help me and other readers (who may find this in the future, seeking the answer like I did) by pointing us to whatever offering that is? 

There was nothing on the pwd site to suggest there was such a paid offering. Again, I did look. :) 

I only asked here because there seemed no other way to ask. As you note, I was asking for ANY solution, including a paid one. 

I'll admit I know nothing about the division of labor there to understand why you might need to close this issue so readily, and especially without identifying how we might go about paying you or whoever for this feature. ::)

**Comment by marcosnils** [comment] 2019-06-23 20:07
> Thanks, but could you please help me and other readers (who may find this in the future, seeking the answer like I did) by pointing us to whatever offering that is?

Oh, sorry about that, I thought that you were asking about the open source version.

> There was nothing on the pwd site to suggest there was such a paid offering. Again, I did look. :)

Yes, that's correct. There's no official docs or info about it. We didn't bootstrap it as a formal company as there are other solutions out there (like qwiklabs) that already offer a similar service and proper customer support. 

Having said that, there are still some customers that work with us that prefer to use and pay for service mostly because it's open source and offers some specific functionalities which others don't. If this is your case, you can contact me directly to marcosnils (at) gmail and we can discuss further options.

> I only asked here because there seemed no other way to ask. As you note, I was asking for ANY solution, including a paid one.

I got it wrong. I apologize.


> I know of no other way to ask for such help. If you'd like to identify that also (if this is not preferred for some situations), that too may help other readers.

No worries. The main reason why I closed the issue is because this specific functionality that you're asking is tailored to some specific needs that really depend on external factors which are not part of the codebase of the project. I admit that I could have provided better guidance instead of closing abruptly. I'll make sure to take it into the account for the next time.
